title: Bin Feng # your name (or website title) here
logo: "/images/profile_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Business Intelligence Engineer at TopRX, LLC 
  <br><br>
  Contact me: 901-206-8312 / binfengmemphis@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/bfeng1/">View My LinkedIn Profile</a> 
  <a href="https://www.kaggle.com/binfeng2021/">View My Kaggle Profile</a> 
  <a href="https://public.tableau.com/app/profile/bin.feng6585/vizzes">View My Tableau Profile</a> 

theme: jekyll-theme-minimal
